name: android-apk build

on: [push, pull_request]

jobs:

  make-apk:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pull the Docker Image
      run: docker pull analogdevices/scopy-build:android
    - name: Run Docker Image
      run: |
            docker run --privileged --net=host \
                -v `pwd`:$GITHUB_WORKSPACE:rw \
                -e "GITHUB_WORKSPACE=$GITHUB_WORKSPACE" \
                -e "BRANCH=${GITHUB_REF#refs/heads/}" \
                analogdevices/scopy-build:android /bin/bash -xe /home/runner/src/scopy-android-deps/clone_and_build.sh
    - uses: actions/upload-artifact@v2
      with:
        name: scopy-android
        path: |
         ${{ github.workspace }}/android-build-debug.apk
         ${{ github.workspace }}/android-build-debug.aab
         ${{ github.workspace }}/android-build-release.aab
