name: Generate Test Report

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Test Report Generator
      run: |
        echo "${{ github.event.pull_request.author }}"
        echo "${{ github.event.pull_request.baseRefName }}"

